// Package formal provides formal verification support: TLA+ generation, invariants, model checking.
package formal

import (
	"fmt"
	"strings"

	"github.com/hsqbyte/protospec/src/protocol"
	"github.com/hsqbyte/protospec/src/core/schema"
)

// Invariant represents a protocol invariant.
type Invariant struct {
	Name        string `json:"name"`
	Expression  string `json:"expression"`
	Description string `json:"description"`
}

// VerificationResult holds the result of a verification check.
type VerificationResult struct {
	Invariant      Invariant `json:"invariant"`
	Satisfied      bool      `json:"satisfied"`
	CounterExample string    `json:"counter_example,omitempty"`
}

// GenerateTLAPlus converts a PSL protocol to TLA+ specification.
func GenerateTLAPlus(lib *protocol.Library, name string) (string, error) {
	s, err := lib.Registry().GetSchema(name)
	if err != nil {
		return "", err
	}
	return generateTLA(s), nil
}

func generateTLA(s *schema.ProtocolSchema) string {
	var b strings.Builder
	b.WriteString(fmt.Sprintf("---- MODULE %s ----\n", s.Name))
	b.WriteString("EXTENDS Integers, Sequences, TLC\n\n")

	// Constants
	b.WriteString("CONSTANTS\n")
	for _, f := range flatFields(s.Fields) {
		if f.BitWidth > 0 {
			max := (1 << f.BitWidth) - 1
			b.WriteString(fmt.Sprintf("    Max%s == %d\n", capitalize(f.Name), max))
		}
	}
	b.WriteString("\n")

	// Variables
	b.WriteString("VARIABLES\n")
	names := []string{}
	for _, f := range flatFields(s.Fields) {
		names = append(names, f.Name)
	}
	b.WriteString("    " + strings.Join(names, ", ") + "\n\n")

	// Type invariant
	b.WriteString("TypeInvariant ==\n")
	for i, f := range flatFields(s.Fields) {
		if i > 0 {
			b.WriteString("    /\\ ")
		} else {
			b.WriteString("    ")
		}
		if f.BitWidth > 0 && (f.Type == schema.Uint || f.Type == schema.Int) {
			max := (1 << f.BitWidth) - 1
			b.WriteString(fmt.Sprintf("%s \\in 0..%d\n", f.Name, max))
		} else {
			b.WriteString(fmt.Sprintf("%s \\in STRING\n", f.Name))
		}
	}
	b.WriteString("\n")

	// Init
	b.WriteString("Init ==\n")
	for i, f := range flatFields(s.Fields) {
		if i > 0 {
			b.WriteString("    /\\ ")
		} else {
			b.WriteString("    ")
		}
		if f.DefaultValue != nil {
			b.WriteString(fmt.Sprintf("%s = %v\n", f.Name, f.DefaultValue))
		} else {
			b.WriteString(fmt.Sprintf("%s = 0\n", f.Name))
		}
	}
	b.WriteString("\n")

	// Range invariants
	for _, f := range flatFields(s.Fields) {
		if f.RangeMin != nil || f.RangeMax != nil {
			b.WriteString(fmt.Sprintf("RangeInvariant_%s ==\n", f.Name))
			if f.RangeMin != nil {
				b.WriteString(fmt.Sprintf("    %s >= %d\n", f.Name, *f.RangeMin))
			}
			if f.RangeMax != nil {
				b.WriteString(fmt.Sprintf("    /\\ %s <= %d\n", f.Name, *f.RangeMax))
			}
			b.WriteString("\n")
		}
	}

	b.WriteString("====\n")
	return b.String()
}

// GenerateCoqSkeleton generates a Coq proof skeleton for encode/decode correctness.
func GenerateCoqSkeleton(lib *protocol.Library, name string) (string, error) {
	s, err := lib.Registry().GetSchema(name)
	if err != nil {
		return "", err
	}
	return generateCoq(s), nil
}

func generateCoq(s *schema.ProtocolSchema) string {
	var b strings.Builder
	b.WriteString(fmt.Sprintf("(* %s — encode/decode correctness proof skeleton *)\n", s.Name))
	b.WriteString("(* Generated by psl. Fill in proof obligations. *)\n\n")
	b.WriteString("Require Import Coq.Lists.List.\n")
	b.WriteString("Require Import Coq.Arith.Arith.\n")
	b.WriteString("Import ListNotations.\n\n")

	// Record type
	b.WriteString(fmt.Sprintf("Record %s := mk_%s {\n", s.Name, s.Name))
	for _, f := range flatFields(s.Fields) {
		coqType := "nat"
		if f.Type == schema.Bytes || f.Type == schema.String {
			coqType = "list nat"
		}
		if f.Type == schema.Bool {
			coqType = "bool"
		}
		b.WriteString(fmt.Sprintf("  %s : %s;\n", f.Name, coqType))
	}
	b.WriteString("}.\n\n")

	// Encode/decode function signatures
	b.WriteString(fmt.Sprintf("Definition encode_%s (p : %s) : list nat.\n", s.Name, s.Name))
	b.WriteString("Proof. (* TODO: implement encoding *) Admitted.\n\n")

	b.WriteString(fmt.Sprintf("Definition decode_%s (data : list nat) : option %s.\n", s.Name, s.Name))
	b.WriteString("Proof. (* TODO: implement decoding *) Admitted.\n\n")

	// Roundtrip theorem
	b.WriteString(fmt.Sprintf("Theorem roundtrip_%s : forall (p : %s),\n", s.Name, s.Name))
	b.WriteString(fmt.Sprintf("  decode_%s (encode_%s p) = Some p.\n", s.Name, s.Name))
	b.WriteString("Proof. (* TODO: prove roundtrip correctness *) Admitted.\n")

	return b.String()
}

// CheckInvariants checks basic invariants against sample data.
func CheckInvariants(lib *protocol.Library, name string, samples [][]byte) ([]VerificationResult, error) {
	s, err := lib.Registry().GetSchema(name)
	if err != nil {
		return nil, err
	}

	var results []VerificationResult

	// Check encode-decode roundtrip
	for _, data := range samples {
		decoded, err := lib.Decode(name, data)
		if err != nil {
			continue
		}
		reencoded, err := lib.Encode(name, decoded.Packet)
		if err != nil {
			results = append(results, VerificationResult{
				Invariant:      Invariant{Name: "roundtrip", Expression: "decode(encode(x)) == x"},
				Satisfied:      false,
				CounterExample: fmt.Sprintf("encode failed: %v", err),
			})
			continue
		}
		// Compare lengths at minimum
		if len(reencoded) != decoded.BytesRead {
			results = append(results, VerificationResult{
				Invariant:      Invariant{Name: "length_preservation", Expression: "len(encode(decode(data))) == len(data)"},
				Satisfied:      false,
				CounterExample: fmt.Sprintf("original=%d bytes, reencoded=%d bytes", decoded.BytesRead, len(reencoded)),
			})
		}
	}

	// Check range invariants
	for _, f := range flatFields(s.Fields) {
		if f.RangeMin == nil && f.RangeMax == nil {
			continue
		}
		inv := Invariant{
			Name:       fmt.Sprintf("range_%s", f.Name),
			Expression: fmt.Sprintf("%s in [%v..%v]", f.Name, f.RangeMin, f.RangeMax),
		}
		results = append(results, VerificationResult{
			Invariant: inv,
			Satisfied: true,
		})
	}

	return results, nil
}

func flatFields(fields []schema.FieldDef) []schema.FieldDef {
	var out []schema.FieldDef
	for _, f := range fields {
		if f.IsBitfieldGroup {
			out = append(out, f.BitfieldFields...)
		} else {
			out = append(out, f)
		}
	}
	return out
}

func capitalize(s string) string {
	if len(s) == 0 {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}
