package codegen

import (
	"fmt"
	"strings"

	"github.com/hsqbyte/protospec/src/core/schema"
)

// GenerateC generates C struct code for the given protocol.
func (g *Generator) GenerateC(name string) (string, error) {
	s, err := g.lib.Registry().GetSchema(name)
	if err != nil {
		return "", fmt.Errorf("C generation only supports binary protocols: %w", err)
	}
	return g.genCBinary(s), nil
}

func (g *Generator) genCBinary(s *schema.ProtocolSchema) string {
	var b strings.Builder
	meta := g.lib.Meta(s.Name)
	guard := strings.ToUpper(s.Name) + "_H"

	b.WriteString("/* Code generated by psl generate. DO NOT EDIT. */\n")
	b.WriteString(fmt.Sprintf("#ifndef %s\n#define %s\n\n", guard, guard))
	b.WriteString("#include <stdint.h>\n#include <stddef.h>\n#include <string.h>\n\n")

	structName := cStructName(s.Name)
	if meta != nil {
		if title, ok := meta.Title["en"]; ok {
			b.WriteString(fmt.Sprintf("/* %s */\n", title))
		}
	}

	// Struct with pragma pack for network protocols
	b.WriteString("#pragma pack(push, 1)\n")
	b.WriteString(fmt.Sprintf("typedef struct {\n"))

	var fields []schema.FieldDef
	for _, f := range s.Fields {
		if f.IsBitfieldGroup {
			fields = append(fields, f.BitfieldFields...)
		} else {
			fields = append(fields, f)
		}
	}

	for _, f := range fields {
		cType := cFieldType(f)
		comment := fieldComment(f, meta)
		if f.Type == schema.Bytes && f.FixedLength > 0 {
			if comment != "" {
				b.WriteString(fmt.Sprintf("    uint8_t %s[%d]; /* %s */\n", f.Name, f.FixedLength, comment))
			} else {
				b.WriteString(fmt.Sprintf("    uint8_t %s[%d];\n", f.Name, f.FixedLength))
			}
		} else if f.Type == schema.Bytes || f.Type == schema.String {
			// Variable-length fields can't be in a packed struct, skip
			continue
		} else if f.BitWidth > 0 && f.BitWidth%8 != 0 {
			// Bitfield
			if comment != "" {
				b.WriteString(fmt.Sprintf("    %s %s : %d; /* %s */\n", cType, f.Name, f.BitWidth, comment))
			} else {
				b.WriteString(fmt.Sprintf("    %s %s : %d;\n", cType, f.Name, f.BitWidth))
			}
		} else {
			if comment != "" {
				b.WriteString(fmt.Sprintf("    %s %s; /* %s */\n", cType, f.Name, comment))
			} else {
				b.WriteString(fmt.Sprintf("    %s %s;\n", cType, f.Name))
			}
		}
	}

	b.WriteString(fmt.Sprintf("} %s;\n", structName))
	b.WriteString("#pragma pack(pop)\n\n")

	// Encode function
	b.WriteString(fmt.Sprintf("static inline size_t %s_encode(const %s *p, uint8_t *buf, size_t len) {\n",
		strings.ToLower(s.Name), structName))
	b.WriteString(fmt.Sprintf("    size_t need = sizeof(%s);\n", structName))
	b.WriteString("    if (len < need) return 0;\n")
	b.WriteString(fmt.Sprintf("    memcpy(buf, p, need);\n"))
	b.WriteString("    return need;\n")
	b.WriteString("}\n\n")

	// Decode function
	b.WriteString(fmt.Sprintf("static inline int %s_decode(const uint8_t *buf, size_t len, %s *p) {\n",
		strings.ToLower(s.Name), structName))
	b.WriteString(fmt.Sprintf("    if (len < sizeof(%s)) return -1;\n", structName))
	b.WriteString(fmt.Sprintf("    memcpy(p, buf, sizeof(%s));\n", structName))
	b.WriteString("    return 0;\n")
	b.WriteString("}\n\n")

	b.WriteString(fmt.Sprintf("#endif /* %s */\n", guard))
	return b.String()
}

func cStructName(name string) string {
	return strings.ToLower(name) + "_t"
}

func cFieldType(f schema.FieldDef) string {
	switch f.Type {
	case schema.Uint:
		switch {
		case f.BitWidth <= 8:
			return "uint8_t"
		case f.BitWidth <= 16:
			return "uint16_t"
		case f.BitWidth <= 32:
			return "uint32_t"
		default:
			return "uint64_t"
		}
	case schema.Int:
		switch {
		case f.BitWidth <= 8:
			return "int8_t"
		case f.BitWidth <= 16:
			return "int16_t"
		case f.BitWidth <= 32:
			return "int32_t"
		default:
			return "int64_t"
		}
	case schema.Bool:
		return "uint8_t"
	default:
		return "uint8_t"
	}
}
