package codegen

import (
	"fmt"
	"strings"

	"github.com/hsqbyte/protospec/src/protocol"
	"github.com/hsqbyte/protospec/src/core/schema"
)

// Generator generates Go source code from a protocol schema.
type Generator struct {
	lib *protocol.Library
}

// NewGenerator creates a new code generator.
func NewGenerator(lib *protocol.Library) *Generator {
	return &Generator{lib: lib}
}

// GenerateGo generates Go source code for the given protocol.
func (g *Generator) GenerateGo(name, pkgName string) (string, error) {
	// Check message protocol first
	if ms := g.lib.Message(name); ms != nil {
		return g.generateGoMessage(ms, pkgName), nil
	}

	s, err := g.lib.Registry().GetSchema(name)
	if err != nil {
		return "", err
	}
	return g.generateGoBinary(s, pkgName), nil
}

func (g *Generator) generateGoBinary(s *schema.ProtocolSchema, pkgName string) string {
	var b strings.Builder
	meta := g.lib.Meta(s.Name)

	b.WriteString("// Code generated by psl generate. DO NOT EDIT.\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", pkgName))
	b.WriteString("import (\n\t\"encoding/binary\"\n\t\"fmt\"\n)\n\n")

	// Struct
	structName := goExportName(s.Name)
	if meta != nil {
		if title, ok := meta.Title["en"]; ok {
			b.WriteString(fmt.Sprintf("// %s represents the %s protocol.\n", structName, title))
		}
	}
	b.WriteString(fmt.Sprintf("type %s struct {\n", structName))

	var fields []schema.FieldDef
	for _, f := range s.Fields {
		if f.IsBitfieldGroup {
			fields = append(fields, f.BitfieldFields...)
		} else {
			fields = append(fields, f)
		}
	}

	for _, f := range fields {
		fieldName := goExportName(f.Name)
		goType := goFieldType(f)
		comment := fieldComment(f, meta)
		if comment != "" {
			b.WriteString(fmt.Sprintf("\t%s %s // %s\n", fieldName, goType, comment))
		} else {
			b.WriteString(fmt.Sprintf("\t%s %s\n", fieldName, goType))
		}
	}
	b.WriteString("}\n\n")

	// Marshal method
	b.WriteString(fmt.Sprintf("// Marshal encodes %s to binary.\n", structName))
	b.WriteString(fmt.Sprintf("func (p *%s) Marshal() ([]byte, error) {\n", structName))
	b.WriteString(g.generateMarshalBody(s, fields))
	b.WriteString("}\n\n")

	// Unmarshal method
	b.WriteString(fmt.Sprintf("// Unmarshal decodes binary data into %s.\n", structName))
	b.WriteString(fmt.Sprintf("func (p *%s) Unmarshal(data []byte) error {\n", structName))
	b.WriteString(g.generateUnmarshalBody(s, fields))
	b.WriteString("}\n")

	return b.String()
}

func (g *Generator) generateMarshalBody(s *schema.ProtocolSchema, fields []schema.FieldDef) string {
	var b strings.Builder
	bo := s.DefaultByteOrder

	// Calculate minimum size
	minBits := 0
	hasVariable := false
	for _, f := range fields {
		if f.BitWidth > 0 {
			minBits += f.BitWidth
		} else {
			hasVariable = true
		}
	}

	if !hasVariable {
		totalBytes := (minBits + 7) / 8
		b.WriteString(fmt.Sprintf("\tbuf := make([]byte, %d)\n", totalBytes))
	} else {
		b.WriteString("\tvar buf []byte\n")
	}

	bitOffset := 0
	for _, f := range fields {
		fieldName := goExportName(f.Name)
		if f.Type == schema.Bytes || f.Type == schema.String {
			if hasVariable {
				b.WriteString(fmt.Sprintf("\tbuf = append(buf, p.%s...)\n", fieldName))
			}
			continue
		}
		if f.BitWidth == 0 {
			continue
		}

		byteOffset := bitOffset / 8
		if f.BitWidth >= 8 && f.BitWidth%8 == 0 && bitOffset%8 == 0 {
			// Byte-aligned field
			switch f.BitWidth {
			case 8:
				b.WriteString(fmt.Sprintf("\tbuf[%d] = byte(p.%s)\n", byteOffset, fieldName))
			case 16:
				if bo == schema.BigEndian {
					b.WriteString(fmt.Sprintf("\tbinary.BigEndian.PutUint16(buf[%d:], uint16(p.%s))\n", byteOffset, fieldName))
				} else {
					b.WriteString(fmt.Sprintf("\tbinary.LittleEndian.PutUint16(buf[%d:], uint16(p.%s))\n", byteOffset, fieldName))
				}
			case 32:
				if bo == schema.BigEndian {
					b.WriteString(fmt.Sprintf("\tbinary.BigEndian.PutUint32(buf[%d:], uint32(p.%s))\n", byteOffset, fieldName))
				} else {
					b.WriteString(fmt.Sprintf("\tbinary.LittleEndian.PutUint32(buf[%d:], uint32(p.%s))\n", byteOffset, fieldName))
				}
			default:
				b.WriteString(fmt.Sprintf("\t// TODO: %s (%d bits)\n", fieldName, f.BitWidth))
			}
		} else {
			b.WriteString(fmt.Sprintf("\t// TODO: bitfield %s (%d bits at offset %d)\n", fieldName, f.BitWidth, bitOffset))
		}
		bitOffset += f.BitWidth
	}

	if !hasVariable {
		b.WriteString("\treturn buf, nil\n")
	} else {
		b.WriteString("\treturn buf, nil\n")
	}
	return b.String()
}

func (g *Generator) generateUnmarshalBody(s *schema.ProtocolSchema, fields []schema.FieldDef) string {
	var b strings.Builder
	bo := s.DefaultByteOrder

	// Calculate minimum size
	minBits := 0
	for _, f := range fields {
		if f.BitWidth > 0 {
			minBits += f.BitWidth
		}
	}
	minBytes := (minBits + 7) / 8
	if minBytes > 0 {
		b.WriteString(fmt.Sprintf("\tif len(data) < %d {\n", minBytes))
		b.WriteString(fmt.Sprintf("\t\treturn fmt.Errorf(\"data too short: need %d bytes, got %%d\", len(data))\n", minBytes))
		b.WriteString("\t}\n")
	}

	bitOffset := 0
	for _, f := range fields {
		fieldName := goExportName(f.Name)
		if f.Type == schema.Bytes || f.Type == schema.String {
			byteOff := bitOffset / 8
			if f.FixedLength > 0 {
				if f.Type == schema.String {
					b.WriteString(fmt.Sprintf("\tp.%s = string(data[%d:%d])\n", fieldName, byteOff, byteOff+f.FixedLength))
				} else {
					b.WriteString(fmt.Sprintf("\tp.%s = make([]byte, %d)\n", fieldName, f.FixedLength))
					b.WriteString(fmt.Sprintf("\tcopy(p.%s, data[%d:%d])\n", fieldName, byteOff, byteOff+f.FixedLength))
				}
				bitOffset += f.FixedLength * 8
			} else {
				// Remaining bytes
				if f.Type == schema.String {
					b.WriteString(fmt.Sprintf("\tp.%s = string(data[%d:])\n", fieldName, byteOff))
				} else {
					b.WriteString(fmt.Sprintf("\tp.%s = data[%d:]\n", fieldName, byteOff))
				}
			}
			continue
		}
		if f.BitWidth == 0 {
			continue
		}

		byteOffset := bitOffset / 8
		if f.BitWidth >= 8 && f.BitWidth%8 == 0 && bitOffset%8 == 0 {
			switch f.BitWidth {
			case 8:
				b.WriteString(fmt.Sprintf("\tp.%s = %s(data[%d])\n", fieldName, goFieldType(f), byteOffset))
			case 16:
				if bo == schema.BigEndian {
					b.WriteString(fmt.Sprintf("\tp.%s = %s(binary.BigEndian.Uint16(data[%d:]))\n", fieldName, goFieldType(f), byteOffset))
				} else {
					b.WriteString(fmt.Sprintf("\tp.%s = %s(binary.LittleEndian.Uint16(data[%d:]))\n", fieldName, goFieldType(f), byteOffset))
				}
			case 32:
				if bo == schema.BigEndian {
					b.WriteString(fmt.Sprintf("\tp.%s = %s(binary.BigEndian.Uint32(data[%d:]))\n", fieldName, goFieldType(f), byteOffset))
				} else {
					b.WriteString(fmt.Sprintf("\tp.%s = %s(binary.LittleEndian.Uint32(data[%d:]))\n", fieldName, goFieldType(f), byteOffset))
				}
			default:
				b.WriteString(fmt.Sprintf("\t// TODO: %s (%d bits)\n", fieldName, f.BitWidth))
			}
		} else {
			b.WriteString(fmt.Sprintf("\t// TODO: bitfield %s (%d bits at offset %d)\n", fieldName, f.BitWidth, bitOffset))
		}
		bitOffset += f.BitWidth
	}

	b.WriteString("\treturn nil\n")
	return b.String()
}

func (g *Generator) generateGoMessage(ms *schema.MessageSchema, pkgName string) string {
	var b strings.Builder
	meta := g.lib.Meta(ms.Name)

	b.WriteString("// Code generated by psl generate. DO NOT EDIT.\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", pkgName))

	if meta != nil {
		if title, ok := meta.Title["en"]; ok {
			b.WriteString(fmt.Sprintf("// %s protocol types — %s\n\n", ms.Name, title))
		}
	}

	for _, msg := range ms.Messages {
		structName := goExportName(msg.Name)
		b.WriteString(fmt.Sprintf("// %s is a %s message.\n", structName, msg.Kind))
		b.WriteString(fmt.Sprintf("type %s struct {\n", structName))
		for _, f := range msg.Fields {
			writeMessageField(&b, f, "\t")
		}
		b.WriteString("}\n\n")
	}

	return b.String()
}

func writeMessageField(b *strings.Builder, f schema.MessageFieldDef, indent string) {
	fieldName := goExportName(f.Name)
	goType := goMessageFieldType(f)
	tag := fmt.Sprintf("`json:\"%s", f.Name)
	if f.Optional {
		tag += ",omitempty"
	}
	tag += "\"`"
	b.WriteString(fmt.Sprintf("%s%s %s %s\n", indent, fieldName, goType, tag))
}

// goExportName converts a snake_case or camelCase name to Go exported PascalCase.
func goExportName(name string) string {
	parts := strings.FieldsFunc(name, func(r rune) bool {
		return r == '_' || r == '-'
	})
	var result strings.Builder
	for _, part := range parts {
		if len(part) == 0 {
			continue
		}
		// Handle common acronyms
		upper := strings.ToUpper(part)
		switch upper {
		case "ID", "IP", "TCP", "UDP", "HTTP", "DNS", "ARP", "MAC", "TTL", "URL", "URI", "TLS", "SSL", "RFC":
			result.WriteString(upper)
		default:
			result.WriteString(strings.ToUpper(part[:1]) + part[1:])
		}
	}
	return result.String()
}

// goFieldType returns the Go type for a binary protocol field.
func goFieldType(f schema.FieldDef) string {
	switch f.Type {
	case schema.Uint:
		switch {
		case f.BitWidth <= 8:
			return "uint8"
		case f.BitWidth <= 16:
			return "uint16"
		case f.BitWidth <= 32:
			return "uint32"
		default:
			return "uint64"
		}
	case schema.Int:
		switch {
		case f.BitWidth <= 8:
			return "int8"
		case f.BitWidth <= 16:
			return "int16"
		case f.BitWidth <= 32:
			return "int32"
		default:
			return "int64"
		}
	case schema.Bool:
		return "bool"
	case schema.Bytes:
		return "[]byte"
	case schema.String:
		return "string"
	default:
		return "any"
	}
}

// goMessageFieldType returns the Go type for a message protocol field.
func goMessageFieldType(f schema.MessageFieldDef) string {
	base := ""
	switch f.Type {
	case schema.MsgString:
		base = "string"
	case schema.MsgNumber:
		base = "float64"
	case schema.MsgBoolean:
		base = "bool"
	case schema.MsgObject:
		if len(f.Fields) > 0 {
			// Inline struct
			var b strings.Builder
			b.WriteString("struct {\n")
			for _, sub := range f.Fields {
				writeMessageField(&b, sub, "\t\t")
			}
			b.WriteString("\t}")
			base = b.String()
		} else {
			base = "map[string]any"
		}
	case schema.MsgArray:
		if f.ItemType != nil {
			base = "[]" + goMessageFieldType(*f.ItemType)
		} else {
			base = "[]any"
		}
	default:
		base = "any"
	}

	if f.Optional && f.Type != schema.MsgObject {
		return "*" + base
	}
	return base
}

// fieldComment returns a comment string for a field based on meta.json.
func fieldComment(f schema.FieldDef, meta *protocol.ProtocolMeta) string {
	if meta == nil {
		return ""
	}
	if fm, ok := meta.Fields[f.Name]; ok {
		if d, ok := fm["en"]; ok {
			return d
		}
	}
	return ""
}
