package codegen

import (
	"fmt"
	"strings"

	"github.com/hsqbyte/protospec/src/schema"
)

// GenerateEmbeddedC generates embedded-friendly C code (no malloc, fixed buffers).
func (g *Generator) GenerateEmbeddedC(name string) (string, error) {
	s, err := g.lib.Registry().GetSchema(name)
	if err != nil {
		return "", err
	}
	return g.embeddedCBinary(s), nil
}

func (g *Generator) embeddedCBinary(s *schema.ProtocolSchema) string {
	var b strings.Builder
	structName := strings.ToUpper(s.Name)

	b.WriteString("/* Generated by psl generate c --embedded. DO NOT EDIT. */\n")
	b.WriteString("/* No dynamic memory allocation — suitable for embedded systems. */\n\n")
	b.WriteString("#ifndef " + structName + "_H\n")
	b.WriteString("#define " + structName + "_H\n\n")
	b.WriteString("#include <stdint.h>\n")
	b.WriteString("#include <stddef.h>\n")
	b.WriteString("#include <string.h>\n\n")

	// Struct with fixed-size buffers
	b.WriteString(fmt.Sprintf("typedef struct {\n"))
	var fields []schema.FieldDef
	for _, f := range s.Fields {
		if f.IsBitfieldGroup {
			fields = append(fields, f.BitfieldFields...)
		} else {
			fields = append(fields, f)
		}
	}

	for _, f := range fields {
		cType := embeddedCType(f)
		b.WriteString(fmt.Sprintf("    %s %s;\n", cType, f.Name))
	}
	b.WriteString(fmt.Sprintf("} %s_t;\n\n", strings.ToLower(s.Name)))

	// Decode function (no malloc)
	b.WriteString(fmt.Sprintf("static inline int %s_decode(%s_t *out, const uint8_t *data, size_t len) {\n",
		strings.ToLower(s.Name), strings.ToLower(s.Name)))

	minBytes := 0
	for _, f := range fields {
		if f.BitWidth > 0 {
			minBytes += (f.BitWidth + 7) / 8
		}
	}
	b.WriteString(fmt.Sprintf("    if (len < %d) return -1;\n", minBytes))
	b.WriteString(fmt.Sprintf("    memset(out, 0, sizeof(%s_t));\n", strings.ToLower(s.Name)))

	offset := 0
	for _, f := range fields {
		if f.Type == schema.Bytes || f.Type == schema.String {
			if f.FixedLength > 0 {
				b.WriteString(fmt.Sprintf("    memcpy(out->%s, data + %d, %d);\n", f.Name, offset, f.FixedLength))
				offset += f.FixedLength
			}
			continue
		}
		if f.BitWidth == 0 {
			continue
		}
		byteWidth := (f.BitWidth + 7) / 8
		switch byteWidth {
		case 1:
			b.WriteString(fmt.Sprintf("    out->%s = data[%d];\n", f.Name, offset))
		case 2:
			if s.DefaultByteOrder == schema.BigEndian {
				b.WriteString(fmt.Sprintf("    out->%s = (uint16_t)data[%d] << 8 | data[%d];\n", f.Name, offset, offset+1))
			} else {
				b.WriteString(fmt.Sprintf("    out->%s = (uint16_t)data[%d+1] << 8 | data[%d];\n", f.Name, offset, offset))
			}
		case 4:
			if s.DefaultByteOrder == schema.BigEndian {
				b.WriteString(fmt.Sprintf("    out->%s = (uint32_t)data[%d] << 24 | (uint32_t)data[%d] << 16 | (uint32_t)data[%d] << 8 | data[%d];\n",
					f.Name, offset, offset+1, offset+2, offset+3))
			} else {
				b.WriteString(fmt.Sprintf("    out->%s = (uint32_t)data[%d+3] << 24 | (uint32_t)data[%d+2] << 16 | (uint32_t)data[%d+1] << 8 | data[%d];\n",
					f.Name, offset, offset, offset, offset))
			}
		}
		offset += byteWidth
	}

	b.WriteString("    return 0;\n}\n\n")

	// Encode function (fixed buffer)
	b.WriteString(fmt.Sprintf("static inline int %s_encode(const %s_t *in, uint8_t *buf, size_t buf_len) {\n",
		strings.ToLower(s.Name), strings.ToLower(s.Name)))
	b.WriteString(fmt.Sprintf("    if (buf_len < %d) return -1;\n", minBytes))
	b.WriteString(fmt.Sprintf("    memset(buf, 0, %d);\n", minBytes))

	offset = 0
	for _, f := range fields {
		if f.Type == schema.Bytes || f.Type == schema.String {
			if f.FixedLength > 0 {
				b.WriteString(fmt.Sprintf("    memcpy(buf + %d, in->%s, %d);\n", offset, f.Name, f.FixedLength))
				offset += f.FixedLength
			}
			continue
		}
		if f.BitWidth == 0 {
			continue
		}
		byteWidth := (f.BitWidth + 7) / 8
		switch byteWidth {
		case 1:
			b.WriteString(fmt.Sprintf("    buf[%d] = (uint8_t)in->%s;\n", offset, f.Name))
		case 2:
			if s.DefaultByteOrder == schema.BigEndian {
				b.WriteString(fmt.Sprintf("    buf[%d] = (uint8_t)(in->%s >> 8); buf[%d] = (uint8_t)in->%s;\n",
					offset, f.Name, offset+1, f.Name))
			} else {
				b.WriteString(fmt.Sprintf("    buf[%d] = (uint8_t)in->%s; buf[%d] = (uint8_t)(in->%s >> 8);\n",
					offset, f.Name, offset+1, f.Name))
			}
		case 4:
			if s.DefaultByteOrder == schema.BigEndian {
				b.WriteString(fmt.Sprintf("    buf[%d] = (uint8_t)(in->%s >> 24); buf[%d] = (uint8_t)(in->%s >> 16); buf[%d] = (uint8_t)(in->%s >> 8); buf[%d] = (uint8_t)in->%s;\n",
					offset, f.Name, offset+1, f.Name, offset+2, f.Name, offset+3, f.Name))
			}
		}
		offset += byteWidth
	}

	b.WriteString(fmt.Sprintf("    return %d;\n}\n\n", minBytes))
	b.WriteString("#endif /* " + structName + "_H */\n")
	return b.String()
}

func embeddedCType(f schema.FieldDef) string {
	switch f.Type {
	case schema.Uint:
		switch {
		case f.BitWidth <= 8:
			return "uint8_t"
		case f.BitWidth <= 16:
			return "uint16_t"
		case f.BitWidth <= 32:
			return "uint32_t"
		default:
			return "uint64_t"
		}
	case schema.Int:
		switch {
		case f.BitWidth <= 8:
			return "int8_t"
		case f.BitWidth <= 16:
			return "int16_t"
		case f.BitWidth <= 32:
			return "int32_t"
		default:
			return "int64_t"
		}
	case schema.Bool:
		return "uint8_t"
	case schema.Bytes:
		if f.FixedLength > 0 {
			return fmt.Sprintf("uint8_t[%d]", f.FixedLength)
		}
		return "uint8_t*"
	case schema.String:
		if f.FixedLength > 0 {
			return fmt.Sprintf("char[%d]", f.FixedLength)
		}
		return "const char*"
	default:
		return "uint8_t"
	}
}
