package codegen

import (
	"fmt"
	"strings"

	"github.com/hsqbyte/protospec/src/core/schema"
)

// GeneratePython generates Python dataclass code for the given protocol.
func (g *Generator) GeneratePython(name string) (string, error) {
	if ms := g.lib.Message(name); ms != nil {
		return g.genPythonMessage(ms), nil
	}
	s, err := g.lib.Registry().GetSchema(name)
	if err != nil {
		return "", err
	}
	return g.genPythonBinary(s), nil
}

func (g *Generator) genPythonBinary(s *schema.ProtocolSchema) string {
	var b strings.Builder
	meta := g.lib.Meta(s.Name)

	b.WriteString("# Code generated by psl generate. DO NOT EDIT.\n")
	b.WriteString("from __future__ import annotations\n")
	b.WriteString("import struct\nfrom dataclasses import dataclass, field\n\n\n")

	className := pyClassName(s.Name)
	if meta != nil {
		if title, ok := meta.Title["en"]; ok {
			b.WriteString(fmt.Sprintf("# %s\n", title))
		}
	}
	b.WriteString("@dataclass\n")
	b.WriteString(fmt.Sprintf("class %s:\n", className))
	b.WriteString(fmt.Sprintf("    \"\"\"Protocol: %s v%s\"\"\"\n\n", s.Name, s.Version))

	var fields []schema.FieldDef
	for _, f := range s.Fields {
		if f.IsBitfieldGroup {
			fields = append(fields, f.BitfieldFields...)
		} else {
			fields = append(fields, f)
		}
	}

	for _, f := range fields {
		pyType := pyFieldType(f)
		comment := fieldComment(f, meta)
		if f.Type == schema.Bytes {
			b.WriteString(fmt.Sprintf("    %s: %s = field(default_factory=bytes)", f.Name, pyType))
		} else {
			b.WriteString(fmt.Sprintf("    %s: %s = 0", f.Name, pyType))
		}
		if comment != "" {
			b.WriteString(fmt.Sprintf("  # %s", comment))
		}
		b.WriteString("\n")
	}

	// pack method
	b.WriteString("\n    def pack(self) -> bytes:\n")
	b.WriteString(g.genPythonPack(s, fields))

	// unpack classmethod
	b.WriteString("\n    @classmethod\n")
	b.WriteString(fmt.Sprintf("    def unpack(cls, data: bytes) -> %s:\n", className))
	b.WriteString(g.genPythonUnpack(s, fields, className))

	return b.String()
}

func (g *Generator) genPythonPack(s *schema.ProtocolSchema, fields []schema.FieldDef) string {
	var b strings.Builder
	bo := s.DefaultByteOrder
	prefix := ">"
	if bo == schema.LittleEndian {
		prefix = "<"
	}

	var fmtChars []string
	var names []string
	for _, f := range fields {
		if f.Type == schema.Bytes || f.Type == schema.String {
			continue
		}
		if f.BitWidth == 0 {
			continue
		}
		fc := pyStructFmt(f)
		if fc != "" {
			fmtChars = append(fmtChars, fc)
			names = append(names, "self."+f.Name)
		}
	}

	if len(fmtChars) > 0 {
		b.WriteString(fmt.Sprintf("        return struct.pack('%s%s', %s)\n",
			prefix, strings.Join(fmtChars, ""), strings.Join(names, ", ")))
	} else {
		b.WriteString("        return b''\n")
	}
	return b.String()
}

func (g *Generator) genPythonUnpack(s *schema.ProtocolSchema, fields []schema.FieldDef, className string) string {
	var b strings.Builder
	bo := s.DefaultByteOrder
	prefix := ">"
	if bo == schema.LittleEndian {
		prefix = "<"
	}

	var fmtChars []string
	var names []string
	for _, f := range fields {
		if f.Type == schema.Bytes || f.Type == schema.String {
			continue
		}
		if f.BitWidth == 0 {
			continue
		}
		fc := pyStructFmt(f)
		if fc != "" {
			fmtChars = append(fmtChars, fc)
			names = append(names, f.Name)
		}
	}

	if len(fmtChars) > 0 {
		fmt_ := prefix + strings.Join(fmtChars, "")
		b.WriteString(fmt.Sprintf("        fmt = '%s'\n", fmt_))
		b.WriteString("        size = struct.calcsize(fmt)\n")
		b.WriteString(fmt.Sprintf("        %s = struct.unpack(fmt, data[:size])\n", strings.Join(names, ", ")))
		b.WriteString(fmt.Sprintf("        return cls(%s)\n", strings.Join(names, ", ")))
	} else {
		b.WriteString(fmt.Sprintf("        return cls()\n"))
	}
	return b.String()
}

func (g *Generator) genPythonMessage(ms *schema.MessageSchema) string {
	var b strings.Builder
	b.WriteString("# Code generated by psl generate. DO NOT EDIT.\n")
	b.WriteString("from __future__ import annotations\n")
	b.WriteString("from dataclasses import dataclass\nfrom typing import Optional, Any, List\n\n\n")

	for _, msg := range ms.Messages {
		className := pyClassName(msg.Name)
		b.WriteString("@dataclass\n")
		b.WriteString(fmt.Sprintf("class %s:\n", className))
		b.WriteString(fmt.Sprintf("    \"\"\"%s message\"\"\"\n", msg.Kind))
		if len(msg.Fields) == 0 {
			b.WriteString("    pass\n\n\n")
			continue
		}
		for _, f := range msg.Fields {
			pyType := pyMsgFieldType(f)
			b.WriteString(fmt.Sprintf("    %s: %s\n", f.Name, pyType))
		}
		b.WriteString("\n\n")
	}
	return b.String()
}

func pyClassName(name string) string {
	parts := strings.FieldsFunc(name, func(r rune) bool {
		return r == '_' || r == '-' || r == ' '
	})
	var result strings.Builder
	for _, p := range parts {
		if len(p) > 0 {
			result.WriteString(strings.ToUpper(p[:1]) + p[1:])
		}
	}
	return result.String()
}

func pyFieldType(f schema.FieldDef) string {
	switch f.Type {
	case schema.Uint, schema.Int:
		return "int"
	case schema.Bool:
		return "bool"
	case schema.Bytes:
		return "bytes"
	case schema.String:
		return "str"
	default:
		return "Any"
	}
}

func pyMsgFieldType(f schema.MessageFieldDef) string {
	base := ""
	switch f.Type {
	case schema.MsgString:
		base = "str"
	case schema.MsgNumber:
		base = "float"
	case schema.MsgBoolean:
		base = "bool"
	case schema.MsgObject:
		base = "dict"
	case schema.MsgArray:
		base = "List[Any]"
	default:
		base = "Any"
	}
	if f.Optional {
		return "Optional[" + base + "]"
	}
	return base
}

func pyStructFmt(f schema.FieldDef) string {
	if f.BitWidth%8 != 0 {
		return ""
	}
	switch f.BitWidth {
	case 8:
		if f.Type == schema.Int {
			return "b"
		}
		return "B"
	case 16:
		if f.Type == schema.Int {
			return "h"
		}
		return "H"
	case 32:
		if f.Type == schema.Int {
			return "i"
		}
		return "I"
	case 64:
		if f.Type == schema.Int {
			return "q"
		}
		return "Q"
	default:
		return ""
	}
}
