package codegen

import (
	"fmt"
	"strings"

	"github.com/hsqbyte/protospec/src/core/schema"
)

// GenerateRust generates Rust struct code for the given protocol.
func (g *Generator) GenerateRust(name string) (string, error) {
	if ms := g.lib.Message(name); ms != nil {
		return g.genRustMessage(ms), nil
	}
	s, err := g.lib.Registry().GetSchema(name)
	if err != nil {
		return "", err
	}
	return g.genRustBinary(s), nil
}

func (g *Generator) genRustBinary(s *schema.ProtocolSchema) string {
	var b strings.Builder
	meta := g.lib.Meta(s.Name)

	b.WriteString("// Code generated by psl generate. DO NOT EDIT.\n\n")

	structName := rustStructName(s.Name)
	if meta != nil {
		if title, ok := meta.Title["en"]; ok {
			b.WriteString(fmt.Sprintf("/// %s protocol.\n", title))
		}
	}
	b.WriteString("#[derive(Debug, Clone, Default)]\n")
	b.WriteString(fmt.Sprintf("pub struct %s {\n", structName))

	var fields []schema.FieldDef
	for _, f := range s.Fields {
		if f.IsBitfieldGroup {
			fields = append(fields, f.BitfieldFields...)
		} else {
			fields = append(fields, f)
		}
	}

	for _, f := range fields {
		rustType := rustFieldType(f)
		comment := fieldComment(f, meta)
		if comment != "" {
			b.WriteString(fmt.Sprintf("    /// %s\n", comment))
		}
		b.WriteString(fmt.Sprintf("    pub %s: %s,\n", rustFieldName(f.Name), rustType))
	}
	b.WriteString("}\n\n")

	// impl block with encode/decode
	b.WriteString(fmt.Sprintf("impl %s {\n", structName))
	b.WriteString("    pub fn encode(&self) -> Vec<u8> {\n")
	b.WriteString("        let mut buf = Vec::new();\n")

	bo := s.DefaultByteOrder
	for _, f := range fields {
		fname := rustFieldName(f.Name)
		if f.Type == schema.Bytes {
			b.WriteString(fmt.Sprintf("        buf.extend_from_slice(&self.%s);\n", fname))
			continue
		}
		if f.Type == schema.String {
			b.WriteString(fmt.Sprintf("        buf.extend_from_slice(self.%s.as_bytes());\n", fname))
			continue
		}
		if f.BitWidth == 0 {
			continue
		}
		if f.BitWidth%8 != 0 {
			b.WriteString(fmt.Sprintf("        // TODO: bitfield %s (%d bits)\n", fname, f.BitWidth))
			continue
		}
		switch f.BitWidth {
		case 8:
			b.WriteString(fmt.Sprintf("        buf.push(self.%s);\n", fname))
		case 16, 32, 64:
			endian := "to_be_bytes"
			if bo == schema.LittleEndian {
				endian = "to_le_bytes"
			}
			b.WriteString(fmt.Sprintf("        buf.extend_from_slice(&self.%s.%s());\n", fname, endian))
		}
	}
	b.WriteString("        buf\n")
	b.WriteString("    }\n\n")

	b.WriteString("    pub fn decode(data: &[u8]) -> Result<Self, &'static str> {\n")
	minBytes := 0
	for _, f := range fields {
		if f.BitWidth > 0 {
			minBytes += f.BitWidth / 8
		}
	}
	if minBytes > 0 {
		b.WriteString(fmt.Sprintf("        if data.len() < %d {\n", minBytes))
		b.WriteString("            return Err(\"data too short\");\n")
		b.WriteString("        }\n")
	}
	b.WriteString("        let mut p = Self::default();\n")

	offset := 0
	for _, f := range fields {
		fname := rustFieldName(f.Name)
		if f.Type == schema.Bytes || f.Type == schema.String {
			if f.FixedLength > 0 {
				if f.Type == schema.String {
					b.WriteString(fmt.Sprintf("        p.%s = String::from_utf8_lossy(&data[%d..%d]).to_string();\n", fname, offset, offset+f.FixedLength))
				} else {
					b.WriteString(fmt.Sprintf("        p.%s = data[%d..%d].to_vec();\n", fname, offset, offset+f.FixedLength))
				}
				offset += f.FixedLength
			} else {
				if f.Type == schema.String {
					b.WriteString(fmt.Sprintf("        p.%s = String::from_utf8_lossy(&data[%d..]).to_string();\n", fname, offset))
				} else {
					b.WriteString(fmt.Sprintf("        p.%s = data[%d..].to_vec();\n", fname, offset))
				}
			}
			continue
		}
		if f.BitWidth == 0 || f.BitWidth%8 != 0 {
			continue
		}
		switch f.BitWidth {
		case 8:
			b.WriteString(fmt.Sprintf("        p.%s = data[%d];\n", fname, offset))
		case 16:
			fn := "from_be_bytes"
			if bo == schema.LittleEndian {
				fn = "from_le_bytes"
			}
			b.WriteString(fmt.Sprintf("        p.%s = u16::%s(data[%d..%d].try_into().unwrap());\n", fname, fn, offset, offset+2))
		case 32:
			fn := "from_be_bytes"
			if bo == schema.LittleEndian {
				fn = "from_le_bytes"
			}
			b.WriteString(fmt.Sprintf("        p.%s = u32::%s(data[%d..%d].try_into().unwrap());\n", fname, fn, offset, offset+4))
		}
		offset += f.BitWidth / 8
	}
	b.WriteString("        Ok(p)\n")
	b.WriteString("    }\n")
	b.WriteString("}\n")

	return b.String()
}

func (g *Generator) genRustMessage(ms *schema.MessageSchema) string {
	var b strings.Builder
	b.WriteString("// Code generated by psl generate. DO NOT EDIT.\n\n")
	b.WriteString("use serde::{Deserialize, Serialize};\n\n")

	for _, msg := range ms.Messages {
		structName := rustStructName(msg.Name)
		b.WriteString(fmt.Sprintf("/// %s message.\n", msg.Kind))
		b.WriteString("#[derive(Debug, Clone, Serialize, Deserialize)]\n")
		b.WriteString(fmt.Sprintf("pub struct %s {\n", structName))
		for _, f := range msg.Fields {
			rustType := rustMsgFieldType(f)
			b.WriteString(fmt.Sprintf("    pub %s: %s,\n", rustFieldName(f.Name), rustType))
		}
		b.WriteString("}\n\n")
	}
	return b.String()
}

func rustStructName(name string) string {
	return goExportName(name) // Same PascalCase logic works
}

func rustFieldName(name string) string {
	// Convert camelCase to snake_case
	var result strings.Builder
	for i, r := range name {
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				result.WriteByte('_')
			}
			result.WriteRune(r + 32)
		} else {
			result.WriteRune(r)
		}
	}
	s := result.String()
	// Rust reserved words
	if s == "type" || s == "match" || s == "ref" || s == "mod" {
		return "r#" + s
	}
	return s
}

func rustFieldType(f schema.FieldDef) string {
	switch f.Type {
	case schema.Uint:
		switch {
		case f.BitWidth <= 8:
			return "u8"
		case f.BitWidth <= 16:
			return "u16"
		case f.BitWidth <= 32:
			return "u32"
		default:
			return "u64"
		}
	case schema.Int:
		switch {
		case f.BitWidth <= 8:
			return "i8"
		case f.BitWidth <= 16:
			return "i16"
		case f.BitWidth <= 32:
			return "i32"
		default:
			return "i64"
		}
	case schema.Bool:
		return "bool"
	case schema.Bytes:
		return "Vec<u8>"
	case schema.String:
		return "String"
	default:
		return "Vec<u8>"
	}
}

func rustMsgFieldType(f schema.MessageFieldDef) string {
	base := ""
	switch f.Type {
	case schema.MsgString:
		base = "String"
	case schema.MsgNumber:
		base = "f64"
	case schema.MsgBoolean:
		base = "bool"
	case schema.MsgObject:
		base = "serde_json::Value"
	case schema.MsgArray:
		base = "Vec<serde_json::Value>"
	default:
		base = "serde_json::Value"
	}
	if f.Optional {
		return "Option<" + base + ">"
	}
	return base
}
