package codegen

import (
	"fmt"
	"strings"

	"github.com/hsqbyte/protospec/src/core/schema"
)

// GenerateTypeScript generates TypeScript type definitions for the given protocol.
func (g *Generator) GenerateTypeScript(name string) (string, error) {
	if ms := g.lib.Message(name); ms != nil {
		return g.genTSMessage(ms), nil
	}
	s, err := g.lib.Registry().GetSchema(name)
	if err != nil {
		return "", err
	}
	return g.genTSBinary(s), nil
}

func (g *Generator) genTSBinary(s *schema.ProtocolSchema) string {
	var b strings.Builder
	meta := g.lib.Meta(s.Name)

	b.WriteString("// Code generated by psl generate. DO NOT EDIT.\n\n")

	ifaceName := goExportName(s.Name)
	if meta != nil {
		if title, ok := meta.Title["en"]; ok {
			b.WriteString(fmt.Sprintf("/** %s protocol. */\n", title))
		}
	}
	b.WriteString(fmt.Sprintf("export interface %s {\n", ifaceName))

	var fields []schema.FieldDef
	for _, f := range s.Fields {
		if f.IsBitfieldGroup {
			fields = append(fields, f.BitfieldFields...)
		} else {
			fields = append(fields, f)
		}
	}

	for _, f := range fields {
		tsType := tsFieldType(f)
		comment := fieldComment(f, meta)
		if comment != "" {
			b.WriteString(fmt.Sprintf("  /** %s */\n", comment))
		}
		b.WriteString(fmt.Sprintf("  %s: %s;\n", f.Name, tsType))
	}
	b.WriteString("}\n\n")

	// Encode function
	b.WriteString(fmt.Sprintf("export function encode%s(p: %s): Buffer {\n", ifaceName, ifaceName))
	b.WriteString(g.genTSEncode(s, fields))
	b.WriteString("}\n\n")

	// Decode function
	b.WriteString(fmt.Sprintf("export function decode%s(buf: Buffer): %s {\n", ifaceName, ifaceName))
	b.WriteString(g.genTSDecode(s, fields))
	b.WriteString("}\n")

	return b.String()
}

func (g *Generator) genTSEncode(s *schema.ProtocolSchema, fields []schema.FieldDef) string {
	var b strings.Builder
	bo := s.DefaultByteOrder

	minBits := 0
	for _, f := range fields {
		if f.BitWidth > 0 {
			minBits += f.BitWidth
		}
	}
	totalBytes := (minBits + 7) / 8
	b.WriteString(fmt.Sprintf("  const buf = Buffer.alloc(%d);\n", totalBytes))

	offset := 0
	for _, f := range fields {
		if f.Type == schema.Bytes || f.Type == schema.String || f.BitWidth == 0 {
			continue
		}
		if f.BitWidth%8 != 0 {
			b.WriteString(fmt.Sprintf("  // TODO: bitfield %s\n", f.Name))
			offset += f.BitWidth
			continue
		}
		byteOff := offset / 8
		switch f.BitWidth {
		case 8:
			b.WriteString(fmt.Sprintf("  buf.writeUInt8(p.%s, %d);\n", f.Name, byteOff))
		case 16:
			if bo == schema.BigEndian {
				b.WriteString(fmt.Sprintf("  buf.writeUInt16BE(p.%s, %d);\n", f.Name, byteOff))
			} else {
				b.WriteString(fmt.Sprintf("  buf.writeUInt16LE(p.%s, %d);\n", f.Name, byteOff))
			}
		case 32:
			if bo == schema.BigEndian {
				b.WriteString(fmt.Sprintf("  buf.writeUInt32BE(p.%s, %d);\n", f.Name, byteOff))
			} else {
				b.WriteString(fmt.Sprintf("  buf.writeUInt32LE(p.%s, %d);\n", f.Name, byteOff))
			}
		}
		offset += f.BitWidth
	}
	b.WriteString("  return buf;\n")
	return b.String()
}

func (g *Generator) genTSDecode(s *schema.ProtocolSchema, fields []schema.FieldDef) string {
	var b strings.Builder
	bo := s.DefaultByteOrder

	b.WriteString("  return {\n")
	offset := 0
	for _, f := range fields {
		if f.Type == schema.Bytes || f.Type == schema.String || f.BitWidth == 0 {
			continue
		}
		if f.BitWidth%8 != 0 {
			b.WriteString(fmt.Sprintf("    %s: 0, // TODO: bitfield\n", f.Name))
			offset += f.BitWidth
			continue
		}
		byteOff := offset / 8
		switch f.BitWidth {
		case 8:
			b.WriteString(fmt.Sprintf("    %s: buf.readUInt8(%d),\n", f.Name, byteOff))
		case 16:
			if bo == schema.BigEndian {
				b.WriteString(fmt.Sprintf("    %s: buf.readUInt16BE(%d),\n", f.Name, byteOff))
			} else {
				b.WriteString(fmt.Sprintf("    %s: buf.readUInt16LE(%d),\n", f.Name, byteOff))
			}
		case 32:
			if bo == schema.BigEndian {
				b.WriteString(fmt.Sprintf("    %s: buf.readUInt32BE(%d),\n", f.Name, byteOff))
			} else {
				b.WriteString(fmt.Sprintf("    %s: buf.readUInt32LE(%d),\n", f.Name, byteOff))
			}
		}
		offset += f.BitWidth
	}
	b.WriteString("  };\n")
	return b.String()
}

func (g *Generator) genTSMessage(ms *schema.MessageSchema) string {
	var b strings.Builder
	b.WriteString("// Code generated by psl generate. DO NOT EDIT.\n\n")

	for _, msg := range ms.Messages {
		ifaceName := goExportName(msg.Name)
		b.WriteString(fmt.Sprintf("/** %s message. */\n", msg.Kind))
		b.WriteString(fmt.Sprintf("export interface %s {\n", ifaceName))
		for _, f := range msg.Fields {
			tsType := tsMsgFieldType(f)
			opt := ""
			if f.Optional {
				opt = "?"
			}
			b.WriteString(fmt.Sprintf("  %s%s: %s;\n", f.Name, opt, tsType))
		}
		b.WriteString("}\n\n")
	}
	return b.String()
}

func tsFieldType(f schema.FieldDef) string {
	switch f.Type {
	case schema.Uint, schema.Int:
		return "number"
	case schema.Bool:
		return "boolean"
	case schema.Bytes:
		return "Buffer"
	case schema.String:
		return "string"
	default:
		return "unknown"
	}
}

func tsMsgFieldType(f schema.MessageFieldDef) string {
	switch f.Type {
	case schema.MsgString:
		return "string"
	case schema.MsgNumber:
		return "number"
	case schema.MsgBoolean:
		return "boolean"
	case schema.MsgObject:
		if len(f.Fields) > 0 {
			var b strings.Builder
			b.WriteString("{ ")
			for i, sub := range f.Fields {
				if i > 0 {
					b.WriteString("; ")
				}
				opt := ""
				if sub.Optional {
					opt = "?"
				}
				b.WriteString(fmt.Sprintf("%s%s: %s", sub.Name, opt, tsMsgFieldType(sub)))
			}
			b.WriteString(" }")
			return b.String()
		}
		return "Record<string, unknown>"
	case schema.MsgArray:
		if f.ItemType != nil {
			return tsMsgFieldType(*f.ItemType) + "[]"
		}
		return "unknown[]"
	default:
		return "unknown"
	}
}
