package codegen

import (
	"fmt"
	"strings"

	"github.com/hsqbyte/protospec/src/core/schema"
)

// GenerateWireshark generates a Lua dissector script for Wireshark.
func (g *Generator) GenerateWireshark(name string) (string, error) {
	s, err := g.lib.Registry().GetSchema(name)
	if err != nil {
		return "", fmt.Errorf("Wireshark generation only supports binary protocols: %w", err)
	}
	return g.genWiresharkLua(s), nil
}

func (g *Generator) genWiresharkLua(s *schema.ProtocolSchema) string {
	var b strings.Builder
	meta := g.lib.Meta(s.Name)
	protoVar := strings.ToLower(s.Name) + "_proto"
	filterName := strings.ToLower(s.Name)

	b.WriteString("-- Code generated by psl generate wireshark. DO NOT EDIT.\n")
	b.WriteString(fmt.Sprintf("-- Protocol: %s v%s\n\n", s.Name, s.Version))

	desc := s.Name + " Protocol"
	if meta != nil {
		if t, ok := meta.Title["en"]; ok {
			desc = t
		}
	}

	b.WriteString(fmt.Sprintf("%s = Proto(\"%s\", \"%s\")\n\n", protoVar, filterName, desc))

	// Fields
	var fields []schema.FieldDef
	for _, f := range s.Fields {
		if f.IsBitfieldGroup {
			fields = append(fields, f.BitfieldFields...)
		} else {
			fields = append(fields, f)
		}
	}

	b.WriteString("-- Protocol fields\n")
	for _, f := range fields {
		wsType := wiresharkFieldType(f)
		fieldVar := fmt.Sprintf("f_%s", f.Name)
		comment := fieldComment(f, meta)
		label := f.Name
		if comment != "" {
			label = comment
		}
		b.WriteString(fmt.Sprintf("%s = ProtoField.%s(\"%s.%s\", \"%s\")\n",
			fieldVar, wsType, filterName, f.Name, label))
	}

	b.WriteString(fmt.Sprintf("\n%s.fields = {", protoVar))
	for i, f := range fields {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(fmt.Sprintf("f_%s", f.Name))
	}
	b.WriteString("}\n\n")

	// Dissector function
	b.WriteString(fmt.Sprintf("function %s.dissector(buffer, pinfo, tree)\n", protoVar))
	b.WriteString(fmt.Sprintf("  pinfo.cols.protocol = \"%s\"\n", s.Name))
	b.WriteString(fmt.Sprintf("  local subtree = tree:add(%s, buffer(), \"%s\")\n\n", protoVar, s.Name))

	offset := 0
	for _, f := range fields {
		if f.Type == schema.Bytes || f.Type == schema.String {
			if f.FixedLength > 0 {
				b.WriteString(fmt.Sprintf("  subtree:add(f_%s, buffer(%d, %d))\n", f.Name, offset, f.FixedLength))
				offset += f.FixedLength
			} else {
				b.WriteString(fmt.Sprintf("  subtree:add(f_%s, buffer(%d))\n", f.Name, offset))
			}
			continue
		}
		if f.BitWidth == 0 || f.BitWidth%8 != 0 {
			continue
		}
		byteLen := f.BitWidth / 8
		b.WriteString(fmt.Sprintf("  subtree:add(f_%s, buffer(%d, %d))\n", f.Name, offset, byteLen))

		// Enum display
		if f.EnumMap != nil {
			b.WriteString(fmt.Sprintf("  -- enum: "))
			for k, v := range f.EnumMap {
				b.WriteString(fmt.Sprintf("%d=%s ", k, v))
			}
			b.WriteString("\n")
		}

		offset += byteLen
	}

	b.WriteString("end\n\n")

	// Register dissector
	if meta != nil && meta.Layer == "transport" {
		b.WriteString("-- Register with IP protocol table\n")
		b.WriteString(fmt.Sprintf("-- local ip_proto = DissectorTable.get(\"ip.proto\")\n"))
		b.WriteString(fmt.Sprintf("-- ip_proto:add(<proto_number>, %s)\n", protoVar))
	}

	return b.String()
}

func wiresharkFieldType(f schema.FieldDef) string {
	switch f.Type {
	case schema.Uint:
		switch {
		case f.BitWidth <= 8:
			return "uint8"
		case f.BitWidth <= 16:
			return "uint16"
		case f.BitWidth <= 32:
			return "uint32"
		default:
			return "uint64"
		}
	case schema.Int:
		switch {
		case f.BitWidth <= 8:
			return "int8"
		case f.BitWidth <= 16:
			return "int16"
		case f.BitWidth <= 32:
			return "int32"
		default:
			return "int64"
		}
	case schema.Bool:
		return "bool"
	case schema.Bytes:
		return "bytes"
	case schema.String:
		return "string"
	default:
		return "bytes"
	}
}
