// Package convert provides protocol format conversion between PSL and other formats.
package convert

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/hsqbyte/protospec/src/protocol"
	"github.com/hsqbyte/protospec/src/schema"
)

// Converter handles protocol format conversions.
type Converter struct {
	lib *protocol.Library
}

// NewConverter creates a new Converter.
func NewConverter(lib *protocol.Library) *Converter {
	return &Converter{lib: lib}
}

// ToProtobuf converts a PSL protocol to Protobuf .proto format.
func (c *Converter) ToProtobuf(name string) (string, error) {
	s, err := c.lib.Registry().GetSchema(name)
	if err != nil {
		return "", err
	}
	return c.binaryToProtobuf(s), nil
}

func (c *Converter) binaryToProtobuf(s *schema.ProtocolSchema) string {
	var b strings.Builder
	b.WriteString("// Generated by psl convert. DO NOT EDIT.\n")
	b.WriteString("syntax = \"proto3\";\n\n")
	b.WriteString(fmt.Sprintf("package %s;\n\n", strings.ToLower(s.Name)))
	b.WriteString(fmt.Sprintf("message %s {\n", s.Name))

	idx := 1
	for _, f := range flatFields(s.Fields) {
		pbType := goToProtoType(f)
		b.WriteString(fmt.Sprintf("  %s %s = %d;\n", pbType, f.Name, idx))
		idx++
	}
	b.WriteString("}\n")
	return b.String()
}

// ToFlatBuffers converts a PSL protocol to FlatBuffers schema.
func (c *Converter) ToFlatBuffers(name string) (string, error) {
	s, err := c.lib.Registry().GetSchema(name)
	if err != nil {
		return "", err
	}
	var b strings.Builder
	b.WriteString("// Generated by psl convert. DO NOT EDIT.\n")
	b.WriteString(fmt.Sprintf("namespace %s;\n\n", s.Name))
	b.WriteString(fmt.Sprintf("table %s {\n", s.Name))
	for _, f := range flatFields(s.Fields) {
		fbType := goToFlatBufType(f)
		b.WriteString(fmt.Sprintf("  %s: %s;\n", f.Name, fbType))
	}
	b.WriteString("}\n\n")
	b.WriteString(fmt.Sprintf("root_type %s;\n", s.Name))
	return b.String(), nil
}

// ToASN1 converts a PSL protocol to ASN.1 notation.
func (c *Converter) ToASN1(name string) (string, error) {
	s, err := c.lib.Registry().GetSchema(name)
	if err != nil {
		return "", err
	}
	var b strings.Builder
	b.WriteString(fmt.Sprintf("%s DEFINITIONS AUTOMATIC TAGS ::= BEGIN\n\n", s.Name))
	b.WriteString(fmt.Sprintf("  %s ::= SEQUENCE {\n", s.Name))
	fields := flatFields(s.Fields)
	for i, f := range fields {
		asn1Type := goToASN1Type(f)
		comma := ","
		if i == len(fields)-1 {
			comma = ""
		}
		b.WriteString(fmt.Sprintf("    %s %s%s\n", f.Name, asn1Type, comma))
	}
	b.WriteString("  }\n\nEND\n")
	return b.String(), nil
}

// ToJSONSchema converts a PSL protocol to JSON Schema.
func (c *Converter) ToJSONSchema(name string) (string, error) {
	// Check message protocol first
	if ms := c.lib.Message(name); ms != nil {
		return c.messageToJSONSchema(ms)
	}
	s, err := c.lib.Registry().GetSchema(name)
	if err != nil {
		return "", err
	}
	return c.binaryToJSONSchema(s)
}

func (c *Converter) binaryToJSONSchema(s *schema.ProtocolSchema) (string, error) {
	sch := map[string]any{
		"$schema":              "https://json-schema.org/draft/2020-12/schema",
		"title":                s.Name,
		"type":                 "object",
		"additionalProperties": false,
	}
	props := map[string]any{}
	var required []string
	for _, f := range flatFields(s.Fields) {
		prop := map[string]any{"type": jsonSchemaType(f)}
		if f.BitWidth > 0 && (f.Type == schema.Uint || f.Type == schema.Int) {
			prop["minimum"] = 0
			prop["maximum"] = (1 << f.BitWidth) - 1
		}
		props[f.Name] = prop
		if f.Condition == nil {
			required = append(required, f.Name)
		}
	}
	sch["properties"] = props
	sch["required"] = required
	data, err := json.MarshalIndent(sch, "", "  ")
	return string(data), err
}

func (c *Converter) messageToJSONSchema(ms *schema.MessageSchema) (string, error) {
	defs := map[string]any{}
	for _, msg := range ms.Messages {
		props := map[string]any{}
		var required []string
		for _, f := range msg.Fields {
			props[f.Name] = msgFieldToJSONSchema(f)
			if !f.Optional {
				required = append(required, f.Name)
			}
		}
		def := map[string]any{
			"type":       "object",
			"properties": props,
		}
		if len(required) > 0 {
			def["required"] = required
		}
		defs[msg.Name] = def
	}
	sch := map[string]any{
		"$schema": "https://json-schema.org/draft/2020-12/schema",
		"title":   ms.Name,
		"$defs":   defs,
	}
	data, err := json.MarshalIndent(sch, "", "  ")
	return string(data), err
}

// ToOpenAPI converts a message PSL to OpenAPI 3.0 spec.
func (c *Converter) ToOpenAPI(name string) (string, error) {
	ms := c.lib.Message(name)
	if ms == nil {
		return "", fmt.Errorf("%s is not a message protocol", name)
	}
	spec := map[string]any{
		"openapi": "3.0.3",
		"info": map[string]any{
			"title":   ms.Name,
			"version": ms.Version,
		},
		"paths": buildOpenAPIPaths(ms),
	}
	data, err := json.MarshalIndent(spec, "", "  ")
	return string(data), err
}

func buildOpenAPIPaths(ms *schema.MessageSchema) map[string]any {
	paths := map[string]any{}
	for _, msg := range ms.Messages {
		if msg.Kind != "request" {
			continue
		}
		path := "/" + strings.ToLower(msg.Name)
		props := map[string]any{}
		for _, f := range msg.Fields {
			props[f.Name] = msgFieldToJSONSchema(f)
		}
		paths[path] = map[string]any{
			"post": map[string]any{
				"summary":     msg.Name,
				"operationId": msg.Name,
				"requestBody": map[string]any{
					"content": map[string]any{
						"application/json": map[string]any{
							"schema": map[string]any{
								"type":       "object",
								"properties": props,
							},
						},
					},
				},
				"responses": map[string]any{
					"200": map[string]any{"description": "OK"},
				},
			},
		}
	}
	return paths
}

// --- Import (reverse conversion) ---

// ImportFromProtobuf parses a .proto file and generates PSL.
func ImportFromProtobuf(protoContent string) (string, error) {
	// Simple parser for proto3 messages
	var b strings.Builder
	lines := strings.Split(protoContent, "\n")
	var msgName string
	inMessage := false

	for _, line := range lines {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "message ") {
			parts := strings.Fields(line)
			if len(parts) >= 2 {
				msgName = parts[1]
				b.WriteString(fmt.Sprintf("protocol %s {\n", msgName))
				b.WriteString("    version \"1.0\";\n")
				b.WriteString("    byte_order big-endian;\n\n")
				inMessage = true
			}
		} else if line == "}" && inMessage {
			b.WriteString("}\n")
			inMessage = false
		} else if inMessage && line != "" && !strings.HasPrefix(line, "//") {
			// Parse field: type name = number;
			parts := strings.Fields(strings.TrimSuffix(line, ";"))
			if len(parts) >= 3 {
				pType := parts[0]
				pName := parts[1]
				pslType := protoToPSLType(pType)
				b.WriteString(fmt.Sprintf("    field %s: %s;\n", pName, pslType))
			}
		}
	}
	if msgName == "" {
		return "", fmt.Errorf("no message found in proto content")
	}
	return b.String(), nil
}

// ImportFromJSONSchema parses a JSON Schema and generates PSL.
func ImportFromJSONSchema(jsonContent string) (string, error) {
	var sch map[string]any
	if err := json.Unmarshal([]byte(jsonContent), &sch); err != nil {
		return "", err
	}
	title, _ := sch["title"].(string)
	if title == "" {
		title = "Imported"
	}
	var b strings.Builder
	b.WriteString(fmt.Sprintf("message %s {\n", title))
	b.WriteString("    version \"1.0\";\n")
	b.WriteString("    transport rest;\n\n")

	if props, ok := sch["properties"].(map[string]any); ok {
		b.WriteString(fmt.Sprintf("    request %sRequest {\n", title))
		for name, prop := range props {
			if pm, ok := prop.(map[string]any); ok {
				t := jsonSchemaToMsgType(pm)
				b.WriteString(fmt.Sprintf("        field %s: %s;\n", name, t))
			}
		}
		b.WriteString("    }\n")
	}
	b.WriteString("}\n")
	return b.String(), nil
}

// --- helpers ---

func flatFields(fields []schema.FieldDef) []schema.FieldDef {
	var out []schema.FieldDef
	for _, f := range fields {
		if f.IsBitfieldGroup {
			out = append(out, f.BitfieldFields...)
		} else {
			out = append(out, f)
		}
	}
	return out
}

func goToProtoType(f schema.FieldDef) string {
	switch f.Type {
	case schema.Uint:
		if f.BitWidth <= 32 {
			return "uint32"
		}
		return "uint64"
	case schema.Int:
		if f.BitWidth <= 32 {
			return "int32"
		}
		return "int64"
	case schema.Bool:
		return "bool"
	case schema.Bytes:
		return "bytes"
	case schema.String:
		return "string"
	default:
		return "bytes"
	}
}

func goToFlatBufType(f schema.FieldDef) string {
	switch f.Type {
	case schema.Uint:
		switch {
		case f.BitWidth <= 8:
			return "ubyte"
		case f.BitWidth <= 16:
			return "ushort"
		case f.BitWidth <= 32:
			return "uint"
		default:
			return "ulong"
		}
	case schema.Int:
		switch {
		case f.BitWidth <= 8:
			return "byte"
		case f.BitWidth <= 16:
			return "short"
		case f.BitWidth <= 32:
			return "int"
		default:
			return "long"
		}
	case schema.Bool:
		return "bool"
	case schema.Bytes:
		return "[ubyte]"
	case schema.String:
		return "string"
	default:
		return "[ubyte]"
	}
}

func goToASN1Type(f schema.FieldDef) string {
	switch f.Type {
	case schema.Uint, schema.Int:
		return "INTEGER"
	case schema.Bool:
		return "BOOLEAN"
	case schema.Bytes:
		return "OCTET STRING"
	case schema.String:
		return "UTF8String"
	default:
		return "OCTET STRING"
	}
}

func jsonSchemaType(f schema.FieldDef) string {
	switch f.Type {
	case schema.Uint, schema.Int:
		return "integer"
	case schema.Bool:
		return "boolean"
	case schema.Bytes:
		return "string" // base64 encoded
	case schema.String:
		return "string"
	default:
		return "string"
	}
}

func msgFieldToJSONSchema(f schema.MessageFieldDef) map[string]any {
	switch f.Type {
	case schema.MsgString:
		return map[string]any{"type": "string"}
	case schema.MsgNumber:
		return map[string]any{"type": "number"}
	case schema.MsgBoolean:
		return map[string]any{"type": "boolean"}
	case schema.MsgObject:
		props := map[string]any{}
		for _, sub := range f.Fields {
			props[sub.Name] = msgFieldToJSONSchema(sub)
		}
		return map[string]any{"type": "object", "properties": props}
	case schema.MsgArray:
		if f.ItemType != nil {
			return map[string]any{"type": "array", "items": msgFieldToJSONSchema(*f.ItemType)}
		}
		return map[string]any{"type": "array"}
	default:
		return map[string]any{}
	}
}

func protoToPSLType(t string) string {
	switch t {
	case "uint32":
		return "uint32"
	case "uint64":
		return "uint64"
	case "int32":
		return "int32"
	case "int64":
		return "int64"
	case "bool":
		return "bool"
	case "string":
		return "string"
	case "bytes":
		return "bytes"
	case "float", "double":
		return "uint32"
	default:
		return "bytes"
	}
}

func jsonSchemaToMsgType(prop map[string]any) string {
	t, _ := prop["type"].(string)
	switch t {
	case "string":
		return "string"
	case "number", "integer":
		return "number"
	case "boolean":
		return "boolean"
	case "object":
		return "object"
	case "array":
		return "array"
	default:
		return "string"
	}
}
